job:
  image: gcr.io/k8s-skaffold/skaffold:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - skaffold build --default-repo $CI_REGISTRY
