version: '3'

services:
  ui:
    build: ./ui
    ports:
      - 3000:80
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:8.0.2-alpine
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./db/sql:/flyway/sql
    depends_on:
      - db

volumes:
  db_data: {}
