apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: web-stack-starter
build:
  artifacts:
  - image: ui
    context: ui
    docker:
      dockerfile: Dockerfile
  - image: api
    context: api
    docker:
      dockerfile: build/Dockerfile
deploy:
  kubectl:
    manifests:
    - ui/deployment.yaml
    - db/deployment.yaml
    - api/deployments/deployment.yaml
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    localPort: 3000
    port: 80