apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: web-stack-starter
build:
  artifacts:
  - image: ui
    context: ui
    docker:
      dockerfile: Dockerfile
  - image: api
    context: api
    docker:
      dockerfile: build/Dockerfile
deploy:
  kustomize: {}
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    localPort: 4000
    port: 80