apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: web-stack-starter
build:
  artifacts:
  - image: ui
    context: ui
    docker:
      dockerfile: Dockerfile
  - image: api
    context: api
    docker:
      dockerfile: build/Dockerfile
deploy:
  kubectl:
    manifests:
    - ui/deployment.yaml
    - db/deployment.yaml
    - api/deployments/deployment.yaml
portForward:
- resourceType: service
  resourceName: ui
  port: 3000
- resourceType: service
  resourceName: db
  port: 5432
- resourceType: service
  resourceName: api
  port: 8080